import React from 'react';
import { Header } from './Header';
import { Footer } from './Footer';

export function TermsAndConditionsPage() {
  return (
    <div>
      <Header />
      
      {/* Page Title Area */}
      <section className="page-title-area attorney-page-title-bg">
        <div className="container">
          <div className="row">
            <div className="col-md-12">
              <div className="page-title-padding">
                <div className="page-title-content text-center">
                  <h1>Terms and Conditions</h1> 
                </div>
                <div className="breadcrumbs text-center">
                  <ul className="page-breadcrumbs">
                    <li><a href="/">Home</a></li>
                    <li><a href="#">Terms and Conditions</a></li>
                  </ul>                        
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Terms and Conditions Content */}
      <div className="privacy-policy-content">
        <div className="container">
          <div className="row">
            <div className="col-md-12">
              <div className="privacy-content">
                <div className="privacy-text">
                  <p>Please read the following 'Terms of Use' very carefully as your use of service is subject to your acceptance of and compliance with the following terms and conditions ("Terms").</p>
                  
                  <p>By using any of our services, you agree that you have read, understood and are bound by the Terms, regardless of how you subscribe to or use our services. If you do not want to be bound by the Terms, you must not subscribe to or use our services.</p>
                  
                  <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules made there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and user agreement for access or usage of the website (www.contracteasily.com) and associated website.</p>
                  
                  <p>Your use of an e-contracts website (including www.contracteasily.com (hereinafter referred to as the "Website") and its related sites, services, Apps and tools) is governed by the terms and conditions as contained in this Agreement applicable to the Website and our subsidiaries and international affiliates. This User Agreement for the Website shall come into effect immediately on your acceptance of terms and conditions and/or first log in onto www.contracteasily.com. It shall continue to remain in force till such time you use the website. contracteasily.com is an internet based portal owned and operated by Contract Easily LLP; a company incorporated under the laws of India.</p>
                  
                  <p>For the purpose of these Terms, Registered User and wherever the context so requires "you", "your" shall mean any natural or legal person who is accessing the Website, its contents and using the services offered on or through the Website and has agreed to become a member of the Website by providing Registration Data (as defined hereinafter) while registering on the Website as Registered User using the computer systems of the Website and accepted this electronic version/electronic record of the Terms of use and has allocated himself/herself a unique identification user name ("User ID" and "Password") to become Registered User. Further, reference to "we", "us", "our", "provider" and "Contract Easily" shall mean Contract Easily LLP (contracteasily.com) and includes its associates, affiliates and subsidiary(ies).</p>
                  
                  <p>The use of the Website is offered to you conditioned on your 'Acceptance' of all the terms, conditions and notices contained in this Terms of use. Upon "Acceptance", these Terms shall be effective and binding upon you along with any amendments made by Provider at its sole discretion and posted on the Website and you shall not claim invalidity of these Terms merely on the grounds that this agreement is being concluded electronically. For the aforesaid purposes, 'Acceptance' shall mean your affirmative action in clicking on 'check box' and on the 'continue button' as provided on the registration page or any act which reflects your use of the Website or the services provided by the Website or any such other actions that implies your acceptance. You hereby further agree that this Agreement is being concluded and executed in India.</p>

                  <h3><strong>Introduction:</strong></h3>
                  <p>www.contracteasily.com is an internet-based content and legal technology portal operated by Contract Easily LLP, a company incorporated under the laws of India.</p>
                  <p>Use of the Website is offered to you conditioned on acceptance without modification of all the terms, conditions and notices contained in these Terms, as may be posted on the Website from time to time. Provider, at its sole discretion, reserves the right not to accept a User from registering on the Website without assigning any reason thereof.</p>

                  <h3><strong>User Account, Password and Security:</strong></h3>
                  <p>You will receive a password and account designation upon completing the Website's registration process. You are responsible for maintaining the confidentiality of the password and account, and are fully responsible for all activities that occur under your password or account. You agree to (a) immediately notify Provider of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session. Provider cannot and will not be liable for any loss or damage arising from your failure to comply with this Section. For viewing the public content on the website you might not require login details, id or password, in those cases you would still be bound by these terms and conditions.</p>

                  <h3><strong>Eligibility to Use the Service:</strong></h3>
                  <p>This website does not cater to the individuals less than 13 years of age, by using this website you represent that you are 13 years or older. That the website contracteasily.com does not intentionally collect personal information from children on our Website. contracteasily.com advises Parental discretion is advised for users in the age group of 14 to 18 years.</p>
                  <p>Any person who shall be considered as incompetent to contract as per the provisions of the Indian Contract Act, 1872, including minors, un-discharged insolvents, etc., are not eligible to use contracteasily.com.</p>
                  <p>Any person using the Services and/or the Indirect Services on behalf of a proprietor/ partnership/ firm/ company, represents and warrants that it is duly authorised to accept the Terms and Conditions and the Policies by the Provider.</p>

                  <h3><strong>Services Offered:</strong></h3>
                  <p>Provider provides a number of Internet-based services through the Web Site (all such services, collectively, the "Service"). One such service enables users to purchase its pre-drafted agreements, and other legal Services. (collectively, "Products").</p>
                  <p>All orders are subject to acceptance by Provider. We reserve the right to reject any order at any time without recourse. We also reserve the right to change the price at any time.</p>
                  <p>Upon acceptance of the order by Provider, the user shall be entitled to download the text of the document.</p>

                  <h3><strong>Payment Terms:</strong></h3>
                  <p>You, as a Buyer, understand that upon initiating a Transaction You are entering into a legally binding and enforceable contract with Provider to purchase the products/services using the Payment Facility, and You shall pay the Transaction Price through Your Issuing Bank to the Provider using Payment Facility.</p>
                  <p>You represent and warrant that if you are purchasing something from the Provider, that you will have the following options of payment:-</p>
                  <p>i) NetBanking<br/>ii) Debit Card<br/>iii) Credit Card<br/>iv) Wallets/UPI</p>
                  <p>You warrant that in case you are making the payment by Credit Card: (i) any credit information you supply is true and complete; (ii) charges incurred by you will be honored by your credit card company; and</p>
                  <p>Provider reserves the right to refuse to process Transactions by Buyers with a prior history of questionable charges including without limitation breach of any agreements by Buyer with Provider or breach/violation of any law or any charges imposed by Issuing Bank or breach of any policy.</p>

                  <h3><strong>Website License:</strong></h3>
                  <p>Subject to your compliance with these terms and conditions, you are hereby granted a non-exclusive, limited, non-transferable, freely revocable license to use the Services as designed. Provider reserves all rights not expressly granted herein in the Terms and Conditions. Provider may terminate this license at any time for any reason or no reason.</p>
                  <p><strong>Intellectual Property Rights:</strong></p>
                  <p>Except as expressly provided in the Terms & Conditions of Use of the Web Site contracteasily.com, nothing contained herein shall be construed as conferring any license or right, by implication, estoppel or otherwise, under copyright or other intellectual property rights.</p>
                  <p>The user agrees that copyrights, trademarks, patents, designs and other proprietary rights and laws protect the Web Site. Any rights not expressly granted herein are reserved.</p>
                  <p>The user is also cautioned against any conduct on his part that infringes or purports to infringe the copyright or other proprietary rights or laws. The user shall not, under any circumstances whatsoever, use the printouts of the material available on this Web Site for any purpose that violates the copyright or any other proprietary rights of the Provider.</p>

                  <h3><strong>Copyright Laws:</strong></h3>
                  <p>Content or information available on the Web Site contracteasily.com is protected by the Copyright Act 1957 and is subject to Provider's Copyright. This Site contains graphics, photographs, images, document layouts, artwork, text, fonts, software tools, and other information (referred to herein as "Content"). This Site and all Content are the copyrighted property of Provider, and/or its subsidiaries (referred to herein as "contracteasily.com") or the copyrighted property of parties from whom Provider has licensed such property. All rights in this Site and its Content are reserved worldwide. It is strictly prohibited to retain, copy, distribute, publish, or use any portion of the Content except as expressly allowed in these Terms of Use. Provider reserves the right to add to, delete from, or modify any part of Content at any time without prior notice.</p>

                  <h3><strong>Limitation on Use:</strong></h3>
                  <p>The User agrees and undertakes not to reverse engineer, modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information or software obtained from the Website. Limited reproduction and copying of the content of the Website is permitted provided that www.contracteasily.com name is stated as the source and prior written permission of Provider is sought. For the removal of doubt, it is clarified that unlimited or wholesale reproduction, copying of the content for commercial or non-commercial purposes and unwarranted modification of data and information within the content of the Website is not permitted.</p>

                  <h3><strong>Termination:</strong></h3>
                  <p>The services so offered by Provider, are subject to the user agreeing to all the terms and conditions of the license. In case any of the terms are revoked, Provider is entitled to terminate this subscription & discontinue the subscriber's right to access the Service.</p>
                  <p><strong>Consequences of Termination:</strong></p>
                  <p>The warranties and indemnities, the provisions in relation to the payment of money due to Provider and the restrictions on the rights of the subscriber in relation to the use of the Database, contained herein shall survive the termination or expiry of this subscription.</p>

                  <h3><strong>User Warranty and Representation:</strong></h3>
                  <p>The user guarantees, warrants, and certifies that you are the owner of the content which you submit or otherwise authorised to use the content and that the content does not infringe upon the property rights, intellectual property rights or other rights of others. You further warrant that to your knowledge, no action, suit, proceeding, or investigation has been instituted or threatened relating to any content, including trademark, trade name service mark, and copyright formerly or currently used by you in connection with the Services rendered by Provider. All the images on the website are copyright protected and any form of reverse engineering, modifying, copying, distributing, transmitting, displaying, performing, reproducing, publishing, licensing, creating derivative works from, transferring, or selling will have legal consequences.</p>
                  <p>User data and information provided may be shared by Panaesha Capital Private Limited with its partners.</p>

                  <h3><strong>Advertisements:</strong></h3>
                  <p>contracteasily.com may contain advertisements and sponsorships. Advertisers and sponsors are responsible for ensuring that material submitted for inclusion on the Web Site is accurate and complies with applicable laws.</p>
                  <p>Provider will not be responsible for the illegality of, or any error or inaccuracy in advertisers or sponsors materials.</p>
                  <p><strong>Privacy:</strong></p>
                  <p>The user of the Web Site contracteasily.com is subject to Website's Privacy Policy available through this link.</p>

                  <h3><strong>Notice:</strong></h3>
                  <p>You agree that Provider may provide all legal communications and notices to you electronically by posting them on our website or, at our election, by sending an e-mail to the e-mail address you provided to us when you registered at our website. You may withdraw your consent to receive communications from us electronically by contacting customer care. However, if you withdraw your consent to receive our communications electronically, you must discontinue your use of your account.</p>

                  <h3><strong>Severability of Provisions:</strong></h3>
                  <p>The Terms and Conditions of Use incorporate by reference, any notices contained on the Web Site, the Privacy Policy, Copyright, Terms and Conditions, which together constitute the entire agreement with respect to access and use of the Web Site. If any provision of the terms of use is unlawful, void or unenforceable, then that provision shall be deemed severable from the remaining provisions and shall not affect the validity and enforceability of the remaining provisions.</p>
                  <p><strong>Indemnification:</strong></p>
                  <p>You agree to indemnify and hold harmless provider from any third party claim, action, demand, loss, or damages (including attorney's fees and costs) arising out of or relating to your violation of these Terms of Use, your use of the Web Site, or your violation of any rights of a third party.</p>

                  <h3><strong>Remedies for Violations:</strong></h3>
                  <p>Contract Easily LLP reserves the right to seek all remedies available at law and equity for violations of the Terms and Conditions of Use, including but not limited to, the right to block access from a particular Internet address to contracteasily.com website and its features.</p>

                  <h3><strong>Governing Law and Jurisdictions:</strong></h3>
                  <p>The Terms and Conditions of Use are governed by and construed in accordance with the laws of India and any action arising out of, or relating to these terms shall be subject to the exclusive jurisdiction of the appropriate Courts in India and you hereby consent and submit to the personal jurisdiction of such courts for the purpose of litigating any such action.</p>
                  <p><strong>Waiver:</strong></p>
                  <p>The failure by either party to enforce at any time or for any period any one or more of the terms and conditions herein shall not be a waiver of them or of the right at any time subsequently to enforce all terms and conditions herein.</p>

                  <h3><strong>Exclusion of Liability:</strong></h3>
                  <p>Provider makes reasonable effort to ensure that the information provided on the Web Site is accurate but does not guarantee or warrants its accuracy, adequacy, correctness, validity, completeness or suitability for any purpose.</p>
                  <p>Provider shall not be liable in contract, tort, delict or otherwise for any loss of whatsoever kind howsoever arising suffered in connection with the Service (whether or not caused by the negligence of provider).</p>
                  <p>Provider shall not be liable in contract, tort, delict or otherwise for any loss of revenue business, anticipated savings or profits, loss of goodwill or data or for any indirect or consequential loss whatsoever, howsoever arising suffered in connection with the Service (whether or not caused by the negligence of provider).</p>

                  <h3><strong>Limitation of Liability:</strong></h3>
                  <p>To the maximum extent permitted by applicable law, in no event shall provider, its affiliates, agents, directors, employees, suppliers or licensors be liable for any direct, indirect, punitive, incidental, special, consequential or exemplary damages, including without limitation damages for loss of profits, goodwill, use, data or other intangible losses, that result from the use of, or inability to use, this services. Under no circumstances will provider be responsible for any damage, loss or injury resulting from hacking, tampering or other unauthorized access or use of the services or your account or the information contained therein.</p>

                  <h3><strong>Link to Other Website and Linking Disclaimer:</strong></h3>
                  <p>Third party Content may appear on the Web Site or may be accessible via links from the Web Site. Provider shall not be responsible for and assumes no liability for any mistakes, misstatements of law, defamation, slander, libel, omissions, falsehood, obscenity, pornography or profanity in the statements, opinions, representations or any other form of Content contained in any third party Content appearing on the Web Site. Provider has no control or authority either over the Content or presentations of the third party thereof, which solely represent the thoughts of the author and is neither endorsed by, nor does it reflect the belief of Provider.</p>
                  <p>Any claim either in contract, tort or otherwise relating to damages, loss, injury or determined caused by, or on account of reliance on such Content, is wholly disclaimed by Provider.</p>

                  <h3><strong>Force Majeure:</strong></h3>
                  <p>Provider's performance under this Agreement is subject to interruption and delay due to causes beyond its reasonable control such as acts of God, acts of any Government, war or other hostility, civil disorder, the elements, fire, explosion, power failure, failure of the Internet and other networks beyond the control of Provider, equipment failure, industrial or labour dispute, inability to obtain essential supplies and the like.</p>

                  <h3><strong>Dispute Resolution:</strong></h3>
                  <p>Any dispute or difference between Provider and Subscriber arising out of or relating to the existence, validity, interpretation, performance or termination of, or otherwise in connection with this Agreement ("Dispute"), shall at first instance be attempted to be amicably settled between the parties through good faith negotiations. Either party shall be entitled to invoke such negotiations by giving to the other party a notice to that effect ("Dispute Notice"). If a Dispute is not resolved by way of good faith negotiations within a period of Sixty (60) days from the date when the Dispute Notice was received by the receiving party then either party shall be entitled to refer the Dispute to arbitration in the manner described below.</p>
                  <p>Any Dispute not resolved by way of good faith negotiations within a period of sixty (60) days from the date when the Dispute Notice was received by the receiving party, shall be finally resolved by arbitration in accordance with the provisions of this clause.</p>
                  <p>The provisions of the Arbitration and Conciliation Act, 1996, as amended ("Arbitration Act"), will apply to such arbitration.</p>
                  <p>The arbitration shall be conducted by a single arbitrator who shall be appointed by the mutual consent of both parties. If the parties are not able to reach a decision to appoint the arbitrator within sixty (60) days of the date when the good faith negotiations mentioned above have failed, then the Dispute shall be referred to a panel of three (3) arbitrators. One (1) arbitrator shall be appointed by each party within thirty (60) days of the parties failing to reach an agreement to appoint the sole arbitrator as aforesaid. The two (2) arbitrators so appointed by the parties shall appoint the third presiding arbitrator within thirty (30) days of their appointment, failing which the third presiding arbitrator shall be appointed in accordance with the provisions of the Arbitration Act.</p>
                  <p>The arbitration proceedings shall be conducted in English.</p>
                  <p>The place of arbitration shall be India.</p>
                  <p>The award of the arbitrator(s) shall be final and binding on both parties. The arbitrator(s) shall state reasons for its/their findings in writing.</p>
                  <p>The costs of arbitration shall be determined by the arbitrator(s).</p>
                  <p>In relation to any arbitration proceedings, the parties agree that the courts in India shall have exclusive jurisdiction to the extent the court has jurisdiction under the Arbitration Act.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
}
